"""
toc.py -- (re)generate the table of contents in optima-history's README.

  python _build/toc.py          -> rewrites the block between the CONTENTS markers in ../optima-history/README.md

Reads the topic folders and each page's own <title>; nothing else. Each folder with lessons becomes a collapsible group
(GitHub renders <details> as click-to-open); folders with no lessons yet share one collapsed group. The first run inserts
the markers under the '## Topic folders' heading; later runs replace only what is between them. optima-history is otherwise
only READ by this project, so review the README change before committing it there.
"""
import os, re, html, sys
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.environ.get('ENC_SRC') or os.path.normpath(os.path.join(HERE, '..', '..'))
LIB = os.path.join(SRC, 'optima-history')
SITE = 'https://optimaondemand.github.io/optima-history/'
START, END = '<!-- CONTENTS:START (generated by the encyclopedia project\'s _build/toc.py; edit the pages, not this list) -->', '<!-- CONTENTS:END -->'

def natkey(s): return [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', s)]
def title_of(path, fallback):
    t = re.search(r'<title[^>]*>(.*?)</title>', open(path, encoding='utf-8', errors='ignore').read(), re.S | re.I)
    s = re.sub(r'\s+', ' ', html.unescape(t.group(1))).strip() if t else ''
    return s or fallback
def md(s): return re.sub(r'([\[\]\\*_`<>|])', r'\\\1', s)
def plural(n, w): return f'{n} {w}' + ('' if n == 1 else 's')

try:   # rough chronological order (earliest first) and date hints, from _meta/topic_order.yml
    import yaml
    ORDER = (yaml.safe_load(open(os.path.join(HERE, '..', '_meta', 'topic_order.yml'), encoding='utf-8')) or {}).get('order', [])
except Exception:
    ORDER = []
rank = {o['folder']: i for i, o in enumerate(ORDER)}; SPAN = {o['folder']: o.get('span', '') for o in ORDER}
folders = sorted((d for d in os.listdir(LIB) if os.path.isdir(os.path.join(LIB, d)) and not d.startswith('.')), key=lambda d: (rank.get(d, 10**6), natkey(d)))
full, empty = [], []; n_l = n_w = 0
for d in folders:
    base = os.path.join(LIB, d)
    lessons = sorted((f for f in os.listdir(base) if f.lower().endswith('.html')), key=natkey)
    wdir = os.path.join(base, 'widgets'); widgets = sorted((f for f in os.listdir(wdir) if f.lower().endswith('.html')), key=natkey) if os.path.isdir(wdir) else []
    (full if lessons or widgets else empty).append((d, lessons, widgets)); n_l += len(lessons); n_w += len(widgets)

out = [f'**{plural(len(folders), "topic folder")} · {plural(n_l, "lesson")} · {plural(n_w, "widget")}.** Folders run in rough chronological order, earliest first (approximate: several span many eras or overlap). Click a folder to open or close it. Lessons open on the live site.', '']
for d, lessons, widgets in full:
    head = plural(len(lessons), 'lesson') + (f' · {plural(len(widgets), "widget")}' if widgets else '')
    out += [f'<details>', f'<summary><b>{d}</b>{" · " + SPAN[d] if SPAN.get(d) else ""} — {head}</summary>', '']
    for f in lessons: out.append(f'- [{md(title_of(os.path.join(LIB, d, f), f))}]({SITE}{d}/{f})')
    if widgets:
        out += ['', '*Widgets embedded by these lessons:*', '']
        for f in widgets: out.append(f'- [{md(title_of(os.path.join(LIB, d, "widgets", f), f))}]({SITE}{d}/widgets/{f})')
    out += ['', f'Scope and boundaries: [{d}/README]({d}/README.md)', '', '</details>', '']
if empty:
    out += ['<details>', f'<summary><b>Not yet populated</b> — {plural(len(empty), "folder")} with a scope note and no lessons</summary>', '']
    for d, _, _ in empty: out.append(f'- [{d}]({d}/README.md)' + (f' — {SPAN[d]}' if SPAN.get(d) else ''))
    out += ['', '</details>', '']
block = START + '\n\n' + '\n'.join(out).rstrip('\n') + '\n\n' + END

p = os.path.join(LIB, 'README.md'); raw = open(p, encoding='utf-8', newline='').read(); crlf = '\r\n' in raw; t = raw.replace('\r\n', '\n')
if START in t and END in t: t = t[:t.index(START)] + block + t[t.index(END) + len(END):]
else:
    a = t.index('## Topic folders'); b = t.index('Each folder has a short README', a)
    t = t[:a] + '## Topic folders and contents\n\n' + block + '\n\n' + t[b:]
open(p, 'w', encoding='utf-8', newline='').write(t.replace('\n', '\r\n') if crlf else t)
print(f'contents written: {len(full)} folders with lessons, {len(empty)} not yet populated, {n_l} lessons, {n_w} widgets')
